services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=true
      - ES_JAVA_OPTS=-Xmx512m
    #     - ELASTIC_PASSWORD=elastic_password123 # Change this password
    deploy:
      resources:
        limits:
          memory: 1024M

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #    - ELASTICSEARCH_USERNAME=elastic
    #    - ELASTICSEARCH_PASSWORD=elastic_password123 # Same as Elasticsearch
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf:ro,Z
      #- ./jvm.options:/usr/share/logstash/config/jvm.options:ro,Z
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.0
    container_name: filebeat
    user: root
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge